apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: ai-agent
data:
  BACKEND: "vllm"
  MODEL_NAME: "speakleash/Bielik-4.5B-v3.0-Instruct"
  VLLM_BASE_URL: "http://vllm-server:8000/v1"
  MCP_URL: "http://mcp-server:8001/mcp"
  OPENAI_API_KEY: "EMPTY"
